name: "Bug反馈"
description: "PCL2 提示 “加载 xaml 出现错误或崩溃”"
labels: [· Bug, 新反馈]
body:
- type: checkboxes
  id: "yml-1"
  attributes:
    label: "检查项"
    description: "请逐个检查下列项目，并勾选确认。"
    options:
    - label: "我已确认该问题不是偶然发生"
      required: true
    - label: "我已在 [Issues 页面](https://github.com/YUANXINGlingyun/ccxaml/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。"
      required: true
- type: textarea
  id: "yml-2"
  attributes:
    label: 描述
    description: "详细描述具体表现。"
  validations:
    required: true
- type: textarea
  id: "yml-3"
  attributes:
    label: 错误报告、日志与附件
    description: "可以上传 PCL 文件夹中的 Log1~5.txt，或者你认为有用的文件"
    placeholder: "先点击这个文本框，然后再将文件直接拖拽到文本框中以上传。"
  validations:
    required: true
